/**
 * @author Alexandros Paraschos
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef NAOYARP_NAOYARPMODULE_H
#define NAOYARP_NAOYARPMODULE_H

#include <alcore/alptr.h>
#include <alcommon/almodule.h>
#include <string>

#include "YarpDev/DeviceManager.h"

namespace AL {

class ALBroker;
}

/**
 * DESCRIBE YOUR CLASS HERE
 */

class NaoYARPModule : public AL::ALModule {

public:

    /**
     * Default Constructor.
     */
    NaoYARPModule ( AL::ALPtr<AL::ALBroker> broker, const std::string& name );

    /**
     * Destructor.
     */
    virtual ~NaoYARPModule();

    /**
     * dummy Function. An autogenerated example method.
     * @param msg Message to show on screen
     * @param foo The method will return this parameter
     * @return The AL::ALValue sent as the foo parameter
     */
    AL::ALValue dummyFunction ( const std::string& msg, const AL::ALValue& foo );

private:
    DeviceManager* dev;
};

#endif  // NAOYARP_NAOYARPMODULE_H

